// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestResolver$Type } from "./TestResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestResolver"]: TestResolver$Type;
    ["contracts/ethregistrar/TestResolver.sol:TestResolver"]: TestResolver$Type;
  }

  interface ContractTypesMap {
    ["TestResolver"]: GetContractReturnType<TestResolver$Type["abi"]>;
    ["contracts/ethregistrar/TestResolver.sol:TestResolver"]: GetContractReturnType<TestResolver$Type["abi"]>;
  }
}
