// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface TestResolver$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "TestResolver",
  "sourceName": "contracts/ethregistrar/TestResolver.sol",
  "abi": [
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "node",
          "type": "bytes32"
        }
      ],
      "name": "addr",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "node",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "addr",
          "type": "address"
        }
      ],
      "name": "setAddr",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes4",
          "name": "interfaceID",
          "type": "bytes4"
        }
      ],
      "name": "supportsInterface",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    }
  ],
  "bytecode": "0x608060405234801561001057600080fd5b506102a6806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806301ffc9a7146100465780633b3b57de1461006e578063d5fa2b00146100c9575b600080fd5b6100596100543660046101c5565b61012c565b60405190151581526020015b60405180910390f35b6100a461007c36600461020e565b60009081526020819052604090205473ffffffffffffffffffffffffffffffffffffffff1690565b60405173ffffffffffffffffffffffffffffffffffffffff9091168152602001610065565b61012a6100d7366004610227565b60009182526020829052604090912080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff909216919091179055565b005b60007f01ffc9a7000000000000000000000000000000000000000000000000000000007fffffffff00000000000000000000000000000000000000000000000000000000831614806101bf57507f3b3b57de000000000000000000000000000000000000000000000000000000007fffffffff000000000000000000000000000000000000000000000000000000008316145b92915050565b6000602082840312156101d757600080fd5b81357fffffffff000000000000000000000000000000000000000000000000000000008116811461020757600080fd5b9392505050565b60006020828403121561022057600080fd5b5035919050565b6000806040838503121561023a57600080fd5b82359150602083013573ffffffffffffffffffffffffffffffffffffffff8116811461026557600080fd5b80915050925092905056fea26469706673582212202a164aa6d8706205e9dc343f8ecf72937b8dd8c4f81fd69f2b7e5c311bb38d1164736f6c63430008110033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b50600436106100415760003560e01c806301ffc9a7146100465780633b3b57de1461006e578063d5fa2b00146100c9575b600080fd5b6100596100543660046101c5565b61012c565b60405190151581526020015b60405180910390f35b6100a461007c36600461020e565b60009081526020819052604090205473ffffffffffffffffffffffffffffffffffffffff1690565b60405173ffffffffffffffffffffffffffffffffffffffff9091168152602001610065565b61012a6100d7366004610227565b60009182526020829052604090912080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff909216919091179055565b005b60007f01ffc9a7000000000000000000000000000000000000000000000000000000007fffffffff00000000000000000000000000000000000000000000000000000000831614806101bf57507f3b3b57de000000000000000000000000000000000000000000000000000000007fffffffff000000000000000000000000000000000000000000000000000000008316145b92915050565b6000602082840312156101d757600080fd5b81357fffffffff000000000000000000000000000000000000000000000000000000008116811461020757600080fd5b9392505050565b60006020828403121561022057600080fd5b5035919050565b6000806040838503121561023a57600080fd5b82359150602083013573ffffffffffffffffffffffffffffffffffffffff8116811461026557600080fd5b80915050925092905056fea26469706673582212202a164aa6d8706205e9dc343f8ecf72937b8dd8c4f81fd69f2b7e5c311bb38d1164736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "TestResolver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TestResolver$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/ethregistrar/TestResolver.sol:TestResolver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TestResolver$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "TestResolver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TestResolver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/ethregistrar/TestResolver.sol:TestResolver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TestResolver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "TestResolver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TestResolver$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/ethregistrar/TestResolver.sol:TestResolver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TestResolver$Type["abi"]>>;
}
