// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SafeMath$Type } from "./SafeMath";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SafeMath"]: SafeMath$Type;
    ["contracts/ethregistrar/SafeMath.sol:SafeMath"]: SafeMath$Type;
  }

  interface ContractTypesMap {
    ["SafeMath"]: GetContractReturnType<SafeMath$Type["abi"]>;
    ["contracts/ethregistrar/SafeMath.sol:SafeMath"]: GetContractReturnType<SafeMath$Type["abi"]>;
  }
}
