// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestBytesUtils$Type } from "./TestBytesUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestBytesUtils"]: TestBytesUtils$Type;
    ["contracts/test/TestBytesUtils.sol:TestBytesUtils"]: TestBytesUtils$Type;
  }

  interface ContractTypesMap {
    ["TestBytesUtils"]: GetContractReturnType<TestBytesUtils$Type["abi"]>;
    ["contracts/test/TestBytesUtils.sol:TestBytesUtils"]: GetContractReturnType<TestBytesUtils$Type["abi"]>;
  }
}
