// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IPriceOracle$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IPriceOracle",
  "sourceName": "contracts/ethregistrar/IPriceOracle.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "name",
          "type": "string"
        },
        {
          "internalType": "uint256",
          "name": "expires",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "duration",
          "type": "uint256"
        }
      ],
      "name": "price",
      "outputs": [
        {
          "components": [
            {
              "internalType": "uint256",
              "name": "base",
              "type": "uint256"
            },
            {
              "internalType": "uint256",
              "name": "premium",
              "type": "uint256"
            }
          ],
          "internalType": "struct IPriceOracle.Price",
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IPriceOracle",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPriceOracle$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/ethregistrar/IPriceOracle.sol:IPriceOracle",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPriceOracle$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IPriceOracle",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPriceOracle$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/ethregistrar/IPriceOracle.sol:IPriceOracle",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPriceOracle$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IPriceOracle",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPriceOracle$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/ethregistrar/IPriceOracle.sol:IPriceOracle",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPriceOracle$Type["abi"]>>;
}
