// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IBulkRenewal$Type } from "./IBulkRenewal";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IBulkRenewal"]: IBulkRenewal$Type;
    ["contracts/ethregistrar/IBulkRenewal.sol:IBulkRenewal"]: IBulkRenewal$Type;
  }

  interface ContractTypesMap {
    ["IBulkRenewal"]: GetContractReturnType<IBulkRenewal$Type["abi"]>;
    ["contracts/ethregistrar/IBulkRenewal.sol:IBulkRenewal"]: GetContractReturnType<IBulkRenewal$Type["abi"]>;
  }
}
