// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IBulkRenewal$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IBulkRenewal",
  "sourceName": "contracts/ethregistrar/IBulkRenewal.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "string[]",
          "name": "names",
          "type": "string[]"
        },
        {
          "internalType": "uint256",
          "name": "duration",
          "type": "uint256"
        }
      ],
      "name": "renewAll",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "string[]",
          "name": "names",
          "type": "string[]"
        },
        {
          "internalType": "uint256",
          "name": "duration",
          "type": "uint256"
        }
      ],
      "name": "rentPrice",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "total",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IBulkRenewal",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IBulkRenewal$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/ethregistrar/IBulkRenewal.sol:IBulkRenewal",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IBulkRenewal$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IBulkRenewal",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IBulkRenewal$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/ethregistrar/IBulkRenewal.sol:IBulkRenewal",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IBulkRenewal$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IBulkRenewal",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IBulkRenewal$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/ethregistrar/IBulkRenewal.sol:IBulkRenewal",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IBulkRenewal$Type["abi"]>>;
}
