// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { INameWrapper$Type } from "./INameWrapper";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["INameWrapper"]: INameWrapper$Type;
    ["contracts/wrapper/INameWrapper.sol:INameWrapper"]: INameWrapper$Type;
  }

  interface ContractTypesMap {
    ["INameWrapper"]: GetContractReturnType<INameWrapper$Type["abi"]>;
    ["contracts/wrapper/INameWrapper.sol:INameWrapper"]: GetContractReturnType<INameWrapper$Type["abi"]>;
  }
}
