// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LegacyResolver$Type } from "./LegacyResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LegacyResolver"]: LegacyResolver$Type;
    ["contracts/test/mocks/LegacyResolver.sol:LegacyResolver"]: LegacyResolver$Type;
  }

  interface ContractTypesMap {
    ["LegacyResolver"]: GetContractReturnType<LegacyResolver$Type["abi"]>;
    ["contracts/test/mocks/LegacyResolver.sol:LegacyResolver"]: GetContractReturnType<LegacyResolver$Type["abi"]>;
  }
}
