// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyOldResolver$Type } from "./DummyOldResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyOldResolver"]: DummyOldResolver$Type;
    ["contracts/utils/DummyOldResolver.sol:DummyOldResolver"]: DummyOldResolver$Type;
  }

  interface ContractTypesMap {
    ["DummyOldResolver"]: GetContractReturnType<DummyOldResolver$Type["abi"]>;
    ["contracts/utils/DummyOldResolver.sol:DummyOldResolver"]: GetContractReturnType<DummyOldResolver$Type["abi"]>;
  }
}
