// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EllipticCurve$Type } from "./EllipticCurve";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EllipticCurve"]: EllipticCurve$Type;
    ["contracts/dnssec-oracle/algorithms/EllipticCurve.sol:EllipticCurve"]: EllipticCurve$Type;
  }

  interface ContractTypesMap {
    ["EllipticCurve"]: GetContractReturnType<EllipticCurve$Type["abi"]>;
    ["contracts/dnssec-oracle/algorithms/EllipticCurve.sol:EllipticCurve"]: GetContractReturnType<EllipticCurve$Type["abi"]>;
  }
}
