// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TLDPublicSuffixList$Type } from "./TLDPublicSuffixList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TLDPublicSuffixList"]: TLDPublicSuffixList$Type;
    ["contracts/dnsregistrar/TLDPublicSuffixList.sol:TLDPublicSuffixList"]: TLDPublicSuffixList$Type;
  }

  interface ContractTypesMap {
    ["TLDPublicSuffixList"]: GetContractReturnType<TLDPublicSuffixList$Type["abi"]>;
    ["contracts/dnsregistrar/TLDPublicSuffixList.sol:TLDPublicSuffixList"]: GetContractReturnType<TLDPublicSuffixList$Type["abi"]>;
  }
}
