// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Resolver$Type } from "./Resolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Resolver"]: Resolver$Type;
    ["contracts/resolvers/Resolver.sol:Resolver"]: Resolver$Type;
  }

  interface ContractTypesMap {
    ["Resolver"]: GetContractReturnType<Resolver$Type["abi"]>;
    ["contracts/resolvers/Resolver.sol:Resolver"]: GetContractReturnType<Resolver$Type["abi"]>;
  }
}
