// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Algorithm$Type } from "./Algorithm";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Algorithm"]: Algorithm$Type;
    ["contracts/dnssec-oracle/algorithms/Algorithm.sol:Algorithm"]: Algorithm$Type;
  }

  interface ContractTypesMap {
    ["Algorithm"]: GetContractReturnType<Algorithm$Type["abi"]>;
    ["contracts/dnssec-oracle/algorithms/Algorithm.sol:Algorithm"]: GetContractReturnType<Algorithm$Type["abi"]>;
  }
}
