// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestRegistrar$Type } from "./TestRegistrar";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestRegistrar"]: TestRegistrar$Type;
    ["contracts/registry/TestRegistrar.sol:TestRegistrar"]: TestRegistrar$Type;
  }

  interface ContractTypesMap {
    ["TestRegistrar"]: GetContractReturnType<TestRegistrar$Type["abi"]>;
    ["contracts/registry/TestRegistrar.sol:TestRegistrar"]: GetContractReturnType<TestRegistrar$Type["abi"]>;
  }
}
