// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestUnwrap$Type } from "./TestUnwrap";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestUnwrap"]: TestUnwrap$Type;
    ["contracts/wrapper/mocks/TestUnwrap.sol:TestUnwrap"]: TestUnwrap$Type;
  }

  interface ContractTypesMap {
    ["TestUnwrap"]: GetContractReturnType<TestUnwrap$Type["abi"]>;
    ["contracts/wrapper/mocks/TestUnwrap.sol:TestUnwrap"]: GetContractReturnType<TestUnwrap$Type["abi"]>;
  }
}
