// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDNSRecordResolver$Type } from "./IDNSRecordResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDNSRecordResolver"]: IDNSRecordResolver$Type;
    ["contracts/resolvers/profiles/IDNSRecordResolver.sol:IDNSRecordResolver"]: IDNSRecordResolver$Type;
  }

  interface ContractTypesMap {
    ["IDNSRecordResolver"]: GetContractReturnType<IDNSRecordResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IDNSRecordResolver.sol:IDNSRecordResolver"]: GetContractReturnType<IDNSRecordResolver$Type["abi"]>;
  }
}
