// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
import { ERC165$Type } from "./ERC165";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "hardhat/types/artifacts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC165"]: ERC165$Type;
    ["@openzeppelin/contracts/utils/introspection/ERC165.sol:ERC165"]: ERC165$Type;
  }

  interface ContractTypesMap {
    ["ERC165"]: GetContractReturnType<ERC165$Type["abi"]>;
    ["@openzeppelin/contracts/utils/introspection/ERC165.sol:ERC165"]: GetContractReturnType<ERC165$Type["abi"]>;
  }
}
