// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExponentialPremiumPriceOracle$Type } from "./ExponentialPremiumPriceOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExponentialPremiumPriceOracle"]: ExponentialPremiumPriceOracle$Type;
    ["contracts/ethregistrar/ExponentialPremiumPriceOracle.sol:ExponentialPremiumPriceOracle"]: ExponentialPremiumPriceOracle$Type;
  }

  interface ContractTypesMap {
    ["ExponentialPremiumPriceOracle"]: GetContractReturnType<ExponentialPremiumPriceOracle$Type["abi"]>;
    ["contracts/ethregistrar/ExponentialPremiumPriceOracle.sol:ExponentialPremiumPriceOracle"]: GetContractReturnType<ExponentialPremiumPriceOracle$Type["abi"]>;
  }
}
