// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BatchGateway$Type } from "./BatchGateway";
import { UniversalResolver$Type } from "./UniversalResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BatchGateway"]: BatchGateway$Type;
    ["UniversalResolver"]: UniversalResolver$Type;
    ["contracts/utils/UniversalResolver.sol:BatchGateway"]: BatchGateway$Type;
    ["contracts/utils/UniversalResolver.sol:UniversalResolver"]: UniversalResolver$Type;
  }

  interface ContractTypesMap {
    ["BatchGateway"]: GetContractReturnType<BatchGateway$Type["abi"]>;
    ["UniversalResolver"]: GetContractReturnType<UniversalResolver$Type["abi"]>;
    ["contracts/utils/UniversalResolver.sol:BatchGateway"]: GetContractReturnType<BatchGateway$Type["abi"]>;
    ["contracts/utils/UniversalResolver.sol:UniversalResolver"]: GetContractReturnType<UniversalResolver$Type["abi"]>;
  }
}
