// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BatchGateway$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BatchGateway",
  "sourceName": "contracts/utils/UniversalResolver.sol",
  "abi": [
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "address",
              "name": "sender",
              "type": "address"
            },
            {
              "internalType": "string[]",
              "name": "urls",
              "type": "string[]"
            },
            {
              "internalType": "bytes",
              "name": "callData",
              "type": "bytes"
            }
          ],
          "internalType": "struct OffchainLookupCallData[]",
          "name": "data",
          "type": "tuple[]"
        }
      ],
      "name": "query",
      "outputs": [
        {
          "internalType": "bool[]",
          "name": "failures",
          "type": "bool[]"
        },
        {
          "internalType": "bytes[]",
          "name": "responses",
          "type": "bytes[]"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BatchGateway",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BatchGateway$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/utils/UniversalResolver.sol:BatchGateway",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BatchGateway$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BatchGateway",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BatchGateway$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/utils/UniversalResolver.sol:BatchGateway",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BatchGateway$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BatchGateway",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BatchGateway$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/utils/UniversalResolver.sol:BatchGateway",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BatchGateway$Type["abi"]>>;
}
