// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SHA1$Type } from "./SHA1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SHA1"]: SHA1$Type;
    ["@ensdomains/solsha1/contracts/SHA1.sol:SHA1"]: SHA1$Type;
  }

  interface ContractTypesMap {
    ["SHA1"]: GetContractReturnType<SHA1$Type["abi"]>;
    ["@ensdomains/solsha1/contracts/SHA1.sol:SHA1"]: GetContractReturnType<SHA1$Type["abi"]>;
  }
}
