// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SHA1$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SHA1",
  "sourceName": "@ensdomains/solsha1/contracts/SHA1.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "x",
          "type": "bytes32"
        }
      ],
      "name": "Debug",
      "type": "event"
    }
  ],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a9dcbd59c18f1aded003fafefb12663f1b10512f02a856ada0b0c1fd23a5c63064736f6c63430008110033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a9dcbd59c18f1aded003fafefb12663f1b10512f02a856ada0b0c1fd23a5c63064736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "@ensdomains/solsha1/contracts/SHA1.sol:SHA1",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SHA1$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "@ensdomains/solsha1/contracts/SHA1.sol:SHA1",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SHA1$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "@ensdomains/solsha1/contracts/SHA1.sol:SHA1",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SHA1$Type["abi"]>>;
}
