// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TextResolver$Type } from "./TextResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TextResolver"]: TextResolver$Type;
    ["contracts/resolvers/profiles/TextResolver.sol:TextResolver"]: TextResolver$Type;
  }

  interface ContractTypesMap {
    ["TextResolver"]: GetContractReturnType<TextResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/TextResolver.sol:TextResolver"]: GetContractReturnType<TextResolver$Type["abi"]>;
  }
}
