// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDNSGateway$Type } from "./IDNSGateway";
import { OffchainDNSResolver$Type } from "./OffchainDNSResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDNSGateway"]: IDNSGateway$Type;
    ["OffchainDNSResolver"]: OffchainDNSResolver$Type;
    ["contracts/dnsregistrar/OffchainDNSResolver.sol:IDNSGateway"]: IDNSGateway$Type;
    ["contracts/dnsregistrar/OffchainDNSResolver.sol:OffchainDNSResolver"]: OffchainDNSResolver$Type;
  }

  interface ContractTypesMap {
    ["IDNSGateway"]: GetContractReturnType<IDNSGateway$Type["abi"]>;
    ["OffchainDNSResolver"]: GetContractReturnType<OffchainDNSResolver$Type["abi"]>;
    ["contracts/dnsregistrar/OffchainDNSResolver.sol:IDNSGateway"]: GetContractReturnType<IDNSGateway$Type["abi"]>;
    ["contracts/dnsregistrar/OffchainDNSResolver.sol:OffchainDNSResolver"]: GetContractReturnType<OffchainDNSResolver$Type["abi"]>;
  }
}
