// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IDNSGateway$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IDNSGateway",
  "sourceName": "contracts/dnsregistrar/OffchainDNSResolver.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "name",
          "type": "bytes"
        },
        {
          "internalType": "uint16",
          "name": "qtype",
          "type": "uint16"
        }
      ],
      "name": "resolve",
      "outputs": [
        {
          "components": [
            {
              "internalType": "bytes",
              "name": "rrset",
              "type": "bytes"
            },
            {
              "internalType": "bytes",
              "name": "sig",
              "type": "bytes"
            }
          ],
          "internalType": "struct DNSSEC.RRSetWithSignature[]",
          "name": "",
          "type": "tuple[]"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IDNSGateway",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IDNSGateway$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/dnsregistrar/OffchainDNSResolver.sol:IDNSGateway",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IDNSGateway$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IDNSGateway",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IDNSGateway$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/dnsregistrar/OffchainDNSResolver.sol:IDNSGateway",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IDNSGateway$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IDNSGateway",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IDNSGateway$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/dnsregistrar/OffchainDNSResolver.sol:IDNSGateway",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IDNSGateway$Type["abi"]>>;
}
