// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMetadataService$Type } from "./IMetadataService";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMetadataService"]: IMetadataService$Type;
    ["contracts/wrapper/IMetadataService.sol:IMetadataService"]: IMetadataService$Type;
  }

  interface ContractTypesMap {
    ["IMetadataService"]: GetContractReturnType<IMetadataService$Type["abi"]>;
    ["contracts/wrapper/IMetadataService.sol:IMetadataService"]: GetContractReturnType<IMetadataService$Type["abi"]>;
  }
}
