// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IMetadataService$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IMetadataService",
  "sourceName": "contracts/wrapper/IMetadataService.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "name": "uri",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IMetadataService",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMetadataService$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/wrapper/IMetadataService.sol:IMetadataService",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMetadataService$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IMetadataService",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMetadataService$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/wrapper/IMetadataService.sol:IMetadataService",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMetadataService$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IMetadataService",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMetadataService$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/wrapper/IMetadataService.sol:IMetadataService",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMetadataService$Type["abi"]>>;
}
