// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PubkeyResolver$Type } from "./PubkeyResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PubkeyResolver"]: PubkeyResolver$Type;
    ["contracts/resolvers/profiles/PubkeyResolver.sol:PubkeyResolver"]: PubkeyResolver$Type;
  }

  interface ContractTypesMap {
    ["PubkeyResolver"]: GetContractReturnType<PubkeyResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/PubkeyResolver.sol:PubkeyResolver"]: GetContractReturnType<PubkeyResolver$Type["abi"]>;
  }
}
