// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Controllable$Type } from "./Controllable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Controllable"]: Controllable$Type;
    ["contracts/wrapper/Controllable.sol:Controllable"]: Controllable$Type;
  }

  interface ContractTypesMap {
    ["Controllable"]: GetContractReturnType<Controllable$Type["abi"]>;
    ["contracts/wrapper/Controllable.sol:Controllable"]: GetContractReturnType<Controllable$Type["abi"]>;
  }
}
