// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExtendedResolver$Type } from "./ExtendedResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExtendedResolver"]: ExtendedResolver$Type;
    ["contracts/resolvers/profiles/ExtendedResolver.sol:ExtendedResolver"]: ExtendedResolver$Type;
  }

  interface ContractTypesMap {
    ["ExtendedResolver"]: GetContractReturnType<ExtendedResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/ExtendedResolver.sol:ExtendedResolver"]: GetContractReturnType<ExtendedResolver$Type["abi"]>;
  }
}
