// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { UpgradedNameWrapperMock$Type } from "./UpgradedNameWrapperMock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UpgradedNameWrapperMock"]: UpgradedNameWrapperMock$Type;
    ["contracts/wrapper/mocks/UpgradedNameWrapperMock.sol:UpgradedNameWrapperMock"]: UpgradedNameWrapperMock$Type;
  }

  interface ContractTypesMap {
    ["UpgradedNameWrapperMock"]: GetContractReturnType<UpgradedNameWrapperMock$Type["abi"]>;
    ["contracts/wrapper/mocks/UpgradedNameWrapperMock.sol:UpgradedNameWrapperMock"]: GetContractReturnType<UpgradedNameWrapperMock$Type["abi"]>;
  }
}
