// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SimplePublicSuffixList$Type } from "./SimplePublicSuffixList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimplePublicSuffixList"]: SimplePublicSuffixList$Type;
    ["contracts/dnsregistrar/SimplePublicSuffixList.sol:SimplePublicSuffixList"]: SimplePublicSuffixList$Type;
  }

  interface ContractTypesMap {
    ["SimplePublicSuffixList"]: GetContractReturnType<SimplePublicSuffixList$Type["abi"]>;
    ["contracts/dnsregistrar/SimplePublicSuffixList.sol:SimplePublicSuffixList"]: GetContractReturnType<SimplePublicSuffixList$Type["abi"]>;
  }
}
