// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ResolverBase$Type } from "./ResolverBase";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ResolverBase"]: ResolverBase$Type;
    ["contracts/resolvers/ResolverBase.sol:ResolverBase"]: ResolverBase$Type;
  }

  interface ContractTypesMap {
    ["ResolverBase"]: GetContractReturnType<ResolverBase$Type["abi"]>;
    ["contracts/resolvers/ResolverBase.sol:ResolverBase"]: GetContractReturnType<ResolverBase$Type["abi"]>;
  }
}
