// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyLegacyTextResolver$Type } from "./DummyLegacyTextResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyLegacyTextResolver"]: DummyLegacyTextResolver$Type;
    ["contracts/dnsregistrar/mocks/DummyLegacyTextResolver.sol:DummyLegacyTextResolver"]: DummyLegacyTextResolver$Type;
  }

  interface ContractTypesMap {
    ["DummyLegacyTextResolver"]: GetContractReturnType<DummyLegacyTextResolver$Type["abi"]>;
    ["contracts/dnsregistrar/mocks/DummyLegacyTextResolver.sol:DummyLegacyTextResolver"]: GetContractReturnType<DummyLegacyTextResolver$Type["abi"]>;
  }
}
