// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SHA256Digest$Type } from "./SHA256Digest";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SHA256Digest"]: SHA256Digest$Type;
    ["contracts/dnssec-oracle/digests/SHA256Digest.sol:SHA256Digest"]: SHA256Digest$Type;
  }

  interface ContractTypesMap {
    ["SHA256Digest"]: GetContractReturnType<SHA256Digest$Type["abi"]>;
    ["contracts/dnssec-oracle/digests/SHA256Digest.sol:SHA256Digest"]: GetContractReturnType<SHA256Digest$Type["abi"]>;
  }
}
