// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Owned$Type } from "./Owned";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Owned"]: Owned$Type;
    ["contracts/dnssec-oracle/Owned.sol:Owned"]: Owned$Type;
  }

  interface ContractTypesMap {
    ["Owned"]: GetContractReturnType<Owned$Type["abi"]>;
    ["contracts/dnssec-oracle/Owned.sol:Owned"]: GetContractReturnType<Owned$Type["abi"]>;
  }
}
