// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Owned$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Owned",
  "sourceName": "contracts/dnssec-oracle/Owned.sol",
  "abi": [
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "newOwner",
          "type": "address"
        }
      ],
      "name": "setOwner",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610177806100326000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806313af40351461003b5780638da5cb5b14610050575b600080fd5b61004e610049366004610104565b610099565b005b6000546100709073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b60005473ffffffffffffffffffffffffffffffffffffffff1633146100bd57600080fd5b600080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff92909216919091179055565b60006020828403121561011657600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461013a57600080fd5b939250505056fea2646970667358221220fa268098ad87be5ad30d765ec352edc37c7056e88f473991d1993613f78cc81264736f6c63430008110033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b50600436106100365760003560e01c806313af40351461003b5780638da5cb5b14610050575b600080fd5b61004e610049366004610104565b610099565b005b6000546100709073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b60005473ffffffffffffffffffffffffffffffffffffffff1633146100bd57600080fd5b600080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff92909216919091179055565b60006020828403121561011657600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461013a57600080fd5b939250505056fea2646970667358221220fa268098ad87be5ad30d765ec352edc37c7056e88f473991d1993613f78cc81264736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Owned",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Owned$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/dnssec-oracle/Owned.sol:Owned",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Owned$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Owned",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Owned$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/dnssec-oracle/Owned.sol:Owned",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Owned$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Owned",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Owned$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/dnssec-oracle/Owned.sol:Owned",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Owned$Type["abi"]>>;
}
