// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyNameWrapper$Type } from "./DummyNameWrapper";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyNameWrapper"]: DummyNameWrapper$Type;
    ["contracts/resolvers/mocks/DummyNameWrapper.sol:DummyNameWrapper"]: DummyNameWrapper$Type;
  }

  interface ContractTypesMap {
    ["DummyNameWrapper"]: GetContractReturnType<DummyNameWrapper$Type["abi"]>;
    ["contracts/resolvers/mocks/DummyNameWrapper.sol:DummyNameWrapper"]: GetContractReturnType<DummyNameWrapper$Type["abi"]>;
  }
}
