// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { P256SHA256Algorithm$Type } from "./P256SHA256Algorithm";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["P256SHA256Algorithm"]: P256SHA256Algorithm$Type;
    ["contracts/dnssec-oracle/algorithms/P256SHA256Algorithm.sol:P256SHA256Algorithm"]: P256SHA256Algorithm$Type;
  }

  interface ContractTypesMap {
    ["P256SHA256Algorithm"]: GetContractReturnType<P256SHA256Algorithm$Type["abi"]>;
    ["contracts/dnssec-oracle/algorithms/P256SHA256Algorithm.sol:P256SHA256Algorithm"]: GetContractReturnType<P256SHA256Algorithm$Type["abi"]>;
  }
}
