// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
import "hardhat/types/artifacts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    SHA1: never;
    NameResolver: never;
    Ownable: never;
    TestBytesUtils: never;
    Controllable: never;
  }

  interface ContractTypesMap {
    SHA1: never;
    NameResolver: never;
    Ownable: never;
    TestBytesUtils: never;
    Controllable: never;
  }
}
