// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyAlgorithm$Type } from "./DummyAlgorithm";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyAlgorithm"]: DummyAlgorithm$Type;
    ["contracts/dnssec-oracle/algorithms/DummyAlgorithm.sol:DummyAlgorithm"]: DummyAlgorithm$Type;
  }

  interface ContractTypesMap {
    ["DummyAlgorithm"]: GetContractReturnType<DummyAlgorithm$Type["abi"]>;
    ["contracts/dnssec-oracle/algorithms/DummyAlgorithm.sol:DummyAlgorithm"]: GetContractReturnType<DummyAlgorithm$Type["abi"]>;
  }
}
