// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ContentHashResolver$Type } from "./ContentHashResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ContentHashResolver"]: ContentHashResolver$Type;
    ["contracts/resolvers/profiles/ContentHashResolver.sol:ContentHashResolver"]: ContentHashResolver$Type;
  }

  interface ContractTypesMap {
    ["ContentHashResolver"]: GetContractReturnType<ContentHashResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/ContentHashResolver.sol:ContentHashResolver"]: GetContractReturnType<ContentHashResolver$Type["abi"]>;
  }
}
