// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestRRUtils$Type } from "./TestRRUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestRRUtils"]: TestRRUtils$Type;
    ["contracts/test/TestRRUtils.sol:TestRRUtils"]: TestRRUtils$Type;
  }

  interface ContractTypesMap {
    ["TestRRUtils"]: GetContractReturnType<TestRRUtils$Type["abi"]>;
    ["contracts/test/TestRRUtils.sol:TestRRUtils"]: GetContractReturnType<TestRRUtils$Type["abi"]>;
  }
}
