// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ModexpPrecompile$Type } from "./ModexpPrecompile";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ModexpPrecompile"]: ModexpPrecompile$Type;
    ["contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol:ModexpPrecompile"]: ModexpPrecompile$Type;
  }

  interface ContractTypesMap {
    ["ModexpPrecompile"]: GetContractReturnType<ModexpPrecompile$Type["abi"]>;
    ["contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol:ModexpPrecompile"]: GetContractReturnType<ModexpPrecompile$Type["abi"]>;
  }
}
