// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ModexpPrecompile$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ModexpPrecompile",
  "sourceName": "contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122097964d2f736978509a1bdbd1a5038511f852c303349cfcdd6a96120bb9d43b9264736f6c63430008110033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122097964d2f736978509a1bdbd1a5038511f852c303349cfcdd6a96120bb9d43b9264736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ModexpPrecompile",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ModexpPrecompile$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol:ModexpPrecompile",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ModexpPrecompile$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ModexpPrecompile",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ModexpPrecompile$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol:ModexpPrecompile",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ModexpPrecompile$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ModexpPrecompile",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ModexpPrecompile$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol:ModexpPrecompile",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ModexpPrecompile$Type["abi"]>>;
}
