// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IExtendedDNSResolver$Type } from "./IExtendedDNSResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IExtendedDNSResolver"]: IExtendedDNSResolver$Type;
    ["contracts/resolvers/profiles/IExtendedDNSResolver.sol:IExtendedDNSResolver"]: IExtendedDNSResolver$Type;
  }

  interface ContractTypesMap {
    ["IExtendedDNSResolver"]: GetContractReturnType<IExtendedDNSResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IExtendedDNSResolver.sol:IExtendedDNSResolver"]: GetContractReturnType<IExtendedDNSResolver$Type["abi"]>;
  }
}
