// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IExtendedDNSResolver$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IExtendedDNSResolver",
  "sourceName": "contracts/resolvers/profiles/IExtendedDNSResolver.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "name",
          "type": "bytes"
        },
        {
          "internalType": "bytes",
          "name": "data",
          "type": "bytes"
        },
        {
          "internalType": "bytes",
          "name": "context",
          "type": "bytes"
        }
      ],
      "name": "resolve",
      "outputs": [
        {
          "internalType": "bytes",
          "name": "",
          "type": "bytes"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IExtendedDNSResolver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IExtendedDNSResolver$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/resolvers/profiles/IExtendedDNSResolver.sol:IExtendedDNSResolver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IExtendedDNSResolver$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IExtendedDNSResolver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IExtendedDNSResolver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/resolvers/profiles/IExtendedDNSResolver.sol:IExtendedDNSResolver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IExtendedDNSResolver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IExtendedDNSResolver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IExtendedDNSResolver$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/resolvers/profiles/IExtendedDNSResolver.sol:IExtendedDNSResolver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IExtendedDNSResolver$Type["abi"]>>;
}
