// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DNSSEC$Type } from "./DNSSEC";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DNSSEC"]: DNSSEC$Type;
    ["contracts/dnssec-oracle/DNSSEC.sol:DNSSEC"]: DNSSEC$Type;
  }

  interface ContractTypesMap {
    ["DNSSEC"]: GetContractReturnType<DNSSEC$Type["abi"]>;
    ["contracts/dnssec-oracle/DNSSEC.sol:DNSSEC"]: GetContractReturnType<DNSSEC$Type["abi"]>;
  }
}
