// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockReverseClaimerImplementer$Type } from "./MockReverseClaimerImplementer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockReverseClaimerImplementer"]: MockReverseClaimerImplementer$Type;
    ["contracts/test/mocks/MockReverseClaimerImplementer.sol:MockReverseClaimerImplementer"]: MockReverseClaimerImplementer$Type;
  }

  interface ContractTypesMap {
    ["MockReverseClaimerImplementer"]: GetContractReturnType<MockReverseClaimerImplementer$Type["abi"]>;
    ["contracts/test/mocks/MockReverseClaimerImplementer.sol:MockReverseClaimerImplementer"]: GetContractReturnType<MockReverseClaimerImplementer$Type["abi"]>;
  }
}
