// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IInterfaceResolver$Type } from "./IInterfaceResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IInterfaceResolver"]: IInterfaceResolver$Type;
    ["contracts/resolvers/profiles/IInterfaceResolver.sol:IInterfaceResolver"]: IInterfaceResolver$Type;
  }

  interface ContractTypesMap {
    ["IInterfaceResolver"]: GetContractReturnType<IInterfaceResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IInterfaceResolver.sol:IInterfaceResolver"]: GetContractReturnType<IInterfaceResolver$Type["abi"]>;
  }
}
