// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { INameWrapperUpgrade$Type } from "./INameWrapperUpgrade";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["INameWrapperUpgrade"]: INameWrapperUpgrade$Type;
    ["contracts/wrapper/INameWrapperUpgrade.sol:INameWrapperUpgrade"]: INameWrapperUpgrade$Type;
  }

  interface ContractTypesMap {
    ["INameWrapperUpgrade"]: GetContractReturnType<INameWrapperUpgrade$Type["abi"]>;
    ["contracts/wrapper/INameWrapperUpgrade.sol:INameWrapperUpgrade"]: GetContractReturnType<INameWrapperUpgrade$Type["abi"]>;
  }
}
