// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface INameWrapperUpgrade$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "INameWrapperUpgrade",
  "sourceName": "contracts/wrapper/INameWrapperUpgrade.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "name",
          "type": "bytes"
        },
        {
          "internalType": "address",
          "name": "wrappedOwner",
          "type": "address"
        },
        {
          "internalType": "uint32",
          "name": "fuses",
          "type": "uint32"
        },
        {
          "internalType": "uint64",
          "name": "expiry",
          "type": "uint64"
        },
        {
          "internalType": "address",
          "name": "approved",
          "type": "address"
        },
        {
          "internalType": "bytes",
          "name": "extraData",
          "type": "bytes"
        }
      ],
      "name": "wrapFromUpgrade",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "INameWrapperUpgrade",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<INameWrapperUpgrade$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/wrapper/INameWrapperUpgrade.sol:INameWrapperUpgrade",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<INameWrapperUpgrade$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "INameWrapperUpgrade",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<INameWrapperUpgrade$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/wrapper/INameWrapperUpgrade.sol:INameWrapperUpgrade",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<INameWrapperUpgrade$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "INameWrapperUpgrade",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<INameWrapperUpgrade$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/wrapper/INameWrapperUpgrade.sol:INameWrapperUpgrade",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<INameWrapperUpgrade$Type["abi"]>>;
}
