// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RSASHA1Algorithm$Type } from "./RSASHA1Algorithm";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RSASHA1Algorithm"]: RSASHA1Algorithm$Type;
    ["contracts/dnssec-oracle/algorithms/RSASHA1Algorithm.sol:RSASHA1Algorithm"]: RSASHA1Algorithm$Type;
  }

  interface ContractTypesMap {
    ["RSASHA1Algorithm"]: GetContractReturnType<RSASHA1Algorithm$Type["abi"]>;
    ["contracts/dnssec-oracle/algorithms/RSASHA1Algorithm.sol:RSASHA1Algorithm"]: GetContractReturnType<RSASHA1Algorithm$Type["abi"]>;
  }
}
