// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestHexUtils$Type } from "./TestHexUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestHexUtils"]: TestHexUtils$Type;
    ["contracts/utils/TestHexUtils.sol:TestHexUtils"]: TestHexUtils$Type;
  }

  interface ContractTypesMap {
    ["TestHexUtils"]: GetContractReturnType<TestHexUtils$Type["abi"]>;
    ["contracts/utils/TestHexUtils.sol:TestHexUtils"]: GetContractReturnType<TestHexUtils$Type["abi"]>;
  }
}
