// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IETHRegistrarController$Type } from "./IETHRegistrarController";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IETHRegistrarController"]: IETHRegistrarController$Type;
    ["contracts/ethregistrar/IETHRegistrarController.sol:IETHRegistrarController"]: IETHRegistrarController$Type;
  }

  interface ContractTypesMap {
    ["IETHRegistrarController"]: GetContractReturnType<IETHRegistrarController$Type["abi"]>;
    ["contracts/ethregistrar/IETHRegistrarController.sol:IETHRegistrarController"]: GetContractReturnType<IETHRegistrarController$Type["abi"]>;
  }
}
