// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RSAVerify$Type } from "./RSAVerify";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RSAVerify"]: RSAVerify$Type;
    ["contracts/dnssec-oracle/algorithms/RSAVerify.sol:RSAVerify"]: RSAVerify$Type;
  }

  interface ContractTypesMap {
    ["RSAVerify"]: GetContractReturnType<RSAVerify$Type["abi"]>;
    ["contracts/dnssec-oracle/algorithms/RSAVerify.sol:RSAVerify"]: GetContractReturnType<RSAVerify$Type["abi"]>;
  }
}
