// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyDNSSEC$Type } from "./DummyDNSSEC";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyDNSSEC"]: DummyDNSSEC$Type;
    ["contracts/dnsregistrar/mocks/DummyDnsRegistrarDNSSEC.sol:DummyDNSSEC"]: DummyDNSSEC$Type;
  }

  interface ContractTypesMap {
    ["DummyDNSSEC"]: GetContractReturnType<DummyDNSSEC$Type["abi"]>;
    ["contracts/dnsregistrar/mocks/DummyDnsRegistrarDNSSEC.sol:DummyDNSSEC"]: GetContractReturnType<DummyDNSSEC$Type["abi"]>;
  }
}
