// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IExtendedResolver$Type } from "./IExtendedResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IExtendedResolver"]: IExtendedResolver$Type;
    ["contracts/resolvers/profiles/IExtendedResolver.sol:IExtendedResolver"]: IExtendedResolver$Type;
  }

  interface ContractTypesMap {
    ["IExtendedResolver"]: GetContractReturnType<IExtendedResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IExtendedResolver.sol:IExtendedResolver"]: GetContractReturnType<IExtendedResolver$Type["abi"]>;
  }
}
