// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1155ReceiverMock$Type } from "./ERC1155ReceiverMock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155ReceiverMock"]: ERC1155ReceiverMock$Type;
    ["contracts/wrapper/mocks/ERC1155ReceiverMock.sol:ERC1155ReceiverMock"]: ERC1155ReceiverMock$Type;
  }

  interface ContractTypesMap {
    ["ERC1155ReceiverMock"]: GetContractReturnType<ERC1155ReceiverMock$Type["abi"]>;
    ["contracts/wrapper/mocks/ERC1155ReceiverMock.sol:ERC1155ReceiverMock"]: GetContractReturnType<ERC1155ReceiverMock$Type["abi"]>;
  }
}
