// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RecordParser$Type } from "./RecordParser";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RecordParser"]: RecordParser$Type;
    ["contracts/dnsregistrar/RecordParser.sol:RecordParser"]: RecordParser$Type;
  }

  interface ContractTypesMap {
    ["RecordParser"]: GetContractReturnType<RecordParser$Type["abi"]>;
    ["contracts/dnsregistrar/RecordParser.sol:RecordParser"]: GetContractReturnType<RecordParser$Type["abi"]>;
  }
}
