// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface RecordParser$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "RecordParser",
  "sourceName": "contracts/dnsregistrar/RecordParser.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f8d31ef242de007659f7db2bbbed2545baa85dc24b67d3338eff42a04a9e5edd64736f6c63430008110033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f8d31ef242de007659f7db2bbbed2545baa85dc24b67d3338eff42a04a9e5edd64736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "RecordParser",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RecordParser$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/dnsregistrar/RecordParser.sol:RecordParser",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RecordParser$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "RecordParser",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RecordParser$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/dnsregistrar/RecordParser.sol:RecordParser",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RecordParser$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "RecordParser",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RecordParser$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/dnsregistrar/RecordParser.sol:RecordParser",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RecordParser$Type["abi"]>>;
}
