// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ENSRegistryWithFallback$Type } from "./ENSRegistryWithFallback";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ENSRegistryWithFallback"]: ENSRegistryWithFallback$Type;
    ["contracts/registry/ENSRegistryWithFallback.sol:ENSRegistryWithFallback"]: ENSRegistryWithFallback$Type;
  }

  interface ContractTypesMap {
    ["ENSRegistryWithFallback"]: GetContractReturnType<ENSRegistryWithFallback$Type["abi"]>;
    ["contracts/registry/ENSRegistryWithFallback.sol:ENSRegistryWithFallback"]: GetContractReturnType<ENSRegistryWithFallback$Type["abi"]>;
  }
}
