// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IReverseRegistrar$Type } from "./IReverseRegistrar";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IReverseRegistrar"]: IReverseRegistrar$Type;
    ["contracts/reverseRegistrar/IReverseRegistrar.sol:IReverseRegistrar"]: IReverseRegistrar$Type;
  }

  interface ContractTypesMap {
    ["IReverseRegistrar"]: GetContractReturnType<IReverseRegistrar$Type["abi"]>;
    ["contracts/reverseRegistrar/IReverseRegistrar.sol:IReverseRegistrar"]: GetContractReturnType<IReverseRegistrar$Type["abi"]>;
  }
}
