// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DNSResolver$Type } from "./DNSResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DNSResolver"]: DNSResolver$Type;
    ["contracts/resolvers/profiles/DNSResolver.sol:DNSResolver"]: DNSResolver$Type;
  }

  interface ContractTypesMap {
    ["DNSResolver"]: GetContractReturnType<DNSResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/DNSResolver.sol:DNSResolver"]: GetContractReturnType<DNSResolver$Type["abi"]>;
  }
}
