// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPubkeyResolver$Type } from "./IPubkeyResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPubkeyResolver"]: IPubkeyResolver$Type;
    ["contracts/resolvers/profiles/IPubkeyResolver.sol:IPubkeyResolver"]: IPubkeyResolver$Type;
  }

  interface ContractTypesMap {
    ["IPubkeyResolver"]: GetContractReturnType<IPubkeyResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IPubkeyResolver.sol:IPubkeyResolver"]: GetContractReturnType<IPubkeyResolver$Type["abi"]>;
  }
}
