// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestNameWrapperReentrancy$Type } from "./TestNameWrapperReentrancy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestNameWrapperReentrancy"]: TestNameWrapperReentrancy$Type;
    ["contracts/wrapper/test/TestNameWrapperReentrancy.sol:TestNameWrapperReentrancy"]: TestNameWrapperReentrancy$Type;
  }

  interface ContractTypesMap {
    ["TestNameWrapperReentrancy"]: GetContractReturnType<TestNameWrapperReentrancy$Type["abi"]>;
    ["contracts/wrapper/test/TestNameWrapperReentrancy.sol:TestNameWrapperReentrancy"]: GetContractReturnType<TestNameWrapperReentrancy$Type["abi"]>;
  }
}
