// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ILinearPremiumPriceOracle$Type } from "./ILinearPremiumPriceOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ILinearPremiumPriceOracle"]: ILinearPremiumPriceOracle$Type;
    ["contracts/ethregistrar/ILinearPremiumPriceOracle.sol:ILinearPremiumPriceOracle"]: ILinearPremiumPriceOracle$Type;
  }

  interface ContractTypesMap {
    ["ILinearPremiumPriceOracle"]: GetContractReturnType<ILinearPremiumPriceOracle$Type["abi"]>;
    ["contracts/ethregistrar/ILinearPremiumPriceOracle.sol:ILinearPremiumPriceOracle"]: GetContractReturnType<ILinearPremiumPriceOracle$Type["abi"]>;
  }
}
