// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ILinearPremiumPriceOracle$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ILinearPremiumPriceOracle",
  "sourceName": "contracts/ethregistrar/ILinearPremiumPriceOracle.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "expires",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "timeUntilPremium",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ILinearPremiumPriceOracle",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ILinearPremiumPriceOracle$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/ethregistrar/ILinearPremiumPriceOracle.sol:ILinearPremiumPriceOracle",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ILinearPremiumPriceOracle$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ILinearPremiumPriceOracle",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ILinearPremiumPriceOracle$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/ethregistrar/ILinearPremiumPriceOracle.sol:ILinearPremiumPriceOracle",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ILinearPremiumPriceOracle$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ILinearPremiumPriceOracle",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ILinearPremiumPriceOracle$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/ethregistrar/ILinearPremiumPriceOracle.sol:ILinearPremiumPriceOracle",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ILinearPremiumPriceOracle$Type["abi"]>>;
}
