// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyExtendedDNSSECResolver$Type } from "./DummyExtendedDNSSECResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyExtendedDNSSECResolver"]: DummyExtendedDNSSECResolver$Type;
    ["contracts/dnsregistrar/mocks/DummyExtendedDNSSECResolver.sol:DummyExtendedDNSSECResolver"]: DummyExtendedDNSSECResolver$Type;
  }

  interface ContractTypesMap {
    ["DummyExtendedDNSSECResolver"]: GetContractReturnType<DummyExtendedDNSSECResolver$Type["abi"]>;
    ["contracts/dnsregistrar/mocks/DummyExtendedDNSSECResolver.sol:DummyExtendedDNSSECResolver"]: GetContractReturnType<DummyExtendedDNSSECResolver$Type["abi"]>;
  }
}
