// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { HexUtils$Type } from "./HexUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HexUtils"]: HexUtils$Type;
    ["contracts/utils/HexUtils.sol:HexUtils"]: HexUtils$Type;
  }

  interface ContractTypesMap {
    ["HexUtils"]: GetContractReturnType<HexUtils$Type["abi"]>;
    ["contracts/utils/HexUtils.sol:HexUtils"]: GetContractReturnType<HexUtils$Type["abi"]>;
  }
}
