// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface HexUtils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "HexUtils",
  "sourceName": "contracts/utils/HexUtils.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220df0479e3fad282d34d4282b94ee08b2fa5d8a621c3be4615eb9921bdfa32f67d64736f6c63430008110033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220df0479e3fad282d34d4282b94ee08b2fa5d8a621c3be4615eb9921bdfa32f67d64736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "HexUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<HexUtils$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/utils/HexUtils.sol:HexUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<HexUtils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "HexUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<HexUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/utils/HexUtils.sol:HexUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<HexUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "HexUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<HexUtils$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/utils/HexUtils.sol:HexUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<HexUtils$Type["abi"]>>;
}
