// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AddrResolver$Type } from "./AddrResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AddrResolver"]: AddrResolver$Type;
    ["contracts/resolvers/profiles/AddrResolver.sol:AddrResolver"]: AddrResolver$Type;
  }

  interface ContractTypesMap {
    ["AddrResolver"]: GetContractReturnType<AddrResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/AddrResolver.sol:AddrResolver"]: GetContractReturnType<AddrResolver$Type["abi"]>;
  }
}
