// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDNSZoneResolver$Type } from "./IDNSZoneResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDNSZoneResolver"]: IDNSZoneResolver$Type;
    ["contracts/resolvers/profiles/IDNSZoneResolver.sol:IDNSZoneResolver"]: IDNSZoneResolver$Type;
  }

  interface ContractTypesMap {
    ["IDNSZoneResolver"]: GetContractReturnType<IDNSZoneResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IDNSZoneResolver.sol:IDNSZoneResolver"]: GetContractReturnType<IDNSZoneResolver$Type["abi"]>;
  }
}
