// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SHA1Digest$Type } from "./SHA1Digest";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SHA1Digest"]: SHA1Digest$Type;
    ["contracts/dnssec-oracle/digests/SHA1Digest.sol:SHA1Digest"]: SHA1Digest$Type;
  }

  interface ContractTypesMap {
    ["SHA1Digest"]: GetContractReturnType<SHA1Digest$Type["abi"]>;
    ["contracts/dnssec-oracle/digests/SHA1Digest.sol:SHA1Digest"]: GetContractReturnType<SHA1Digest$Type["abi"]>;
  }
}
