// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ABIResolver$Type } from "./ABIResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ABIResolver"]: ABIResolver$Type;
    ["contracts/resolvers/profiles/ABIResolver.sol:ABIResolver"]: ABIResolver$Type;
  }

  interface ContractTypesMap {
    ["ABIResolver"]: GetContractReturnType<ABIResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/ABIResolver.sol:ABIResolver"]: GetContractReturnType<ABIResolver$Type["abi"]>;
  }
}
