// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TestNameEncoder$Type } from "./TestNameEncoder";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestNameEncoder"]: TestNameEncoder$Type;
    ["contracts/utils/TestNameEncoder.sol:TestNameEncoder"]: TestNameEncoder$Type;
  }

  interface ContractTypesMap {
    ["TestNameEncoder"]: GetContractReturnType<TestNameEncoder$Type["abi"]>;
    ["contracts/utils/TestNameEncoder.sol:TestNameEncoder"]: GetContractReturnType<TestNameEncoder$Type["abi"]>;
  }
}
