// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Multicallable$Type } from "./Multicallable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Multicallable"]: Multicallable$Type;
    ["contracts/resolvers/Multicallable.sol:Multicallable"]: Multicallable$Type;
  }

  interface ContractTypesMap {
    ["Multicallable"]: GetContractReturnType<Multicallable$Type["abi"]>;
    ["contracts/resolvers/Multicallable.sol:Multicallable"]: GetContractReturnType<Multicallable$Type["abi"]>;
  }
}
