// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface NameResolver$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "NameResolver",
  "sourceName": "contracts/reverseRegistrar/ReverseRegistrar.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "node",
          "type": "bytes32"
        },
        {
          "internalType": "string",
          "name": "name",
          "type": "string"
        }
      ],
      "name": "setName",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "contracts/reverseRegistrar/ReverseRegistrar.sol:NameResolver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<NameResolver$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "contracts/reverseRegistrar/ReverseRegistrar.sol:NameResolver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<NameResolver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "contracts/reverseRegistrar/ReverseRegistrar.sol:NameResolver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<NameResolver$Type["abi"]>>;
}
