// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IContentHashResolver$Type } from "./IContentHashResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IContentHashResolver"]: IContentHashResolver$Type;
    ["contracts/resolvers/profiles/IContentHashResolver.sol:IContentHashResolver"]: IContentHashResolver$Type;
  }

  interface ContractTypesMap {
    ["IContentHashResolver"]: GetContractReturnType<IContentHashResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IContentHashResolver.sol:IContentHashResolver"]: GetContractReturnType<IContentHashResolver$Type["abi"]>;
  }
}
