// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IContentHashResolver$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IContentHashResolver",
  "sourceName": "contracts/resolvers/profiles/IContentHashResolver.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "node",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "bytes",
          "name": "hash",
          "type": "bytes"
        }
      ],
      "name": "ContenthashChanged",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "node",
          "type": "bytes32"
        }
      ],
      "name": "contenthash",
      "outputs": [
        {
          "internalType": "bytes",
          "name": "",
          "type": "bytes"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IContentHashResolver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IContentHashResolver$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/resolvers/profiles/IContentHashResolver.sol:IContentHashResolver",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IContentHashResolver$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IContentHashResolver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IContentHashResolver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/resolvers/profiles/IContentHashResolver.sol:IContentHashResolver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IContentHashResolver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IContentHashResolver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IContentHashResolver$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/resolvers/profiles/IContentHashResolver.sol:IContentHashResolver",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IContentHashResolver$Type["abi"]>>;
}
