// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockOffchainResolver$Type } from "./MockOffchainResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockOffchainResolver"]: MockOffchainResolver$Type;
    ["contracts/test/mocks/MockOffchainResolver.sol:MockOffchainResolver"]: MockOffchainResolver$Type;
  }

  interface ContractTypesMap {
    ["MockOffchainResolver"]: GetContractReturnType<MockOffchainResolver$Type["abi"]>;
    ["contracts/test/mocks/MockOffchainResolver.sol:MockOffchainResolver"]: GetContractReturnType<MockOffchainResolver$Type["abi"]>;
  }
}
