// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NameGriefer$Type } from "./NameGriefer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NameGriefer"]: NameGriefer$Type;
    ["contracts/wrapper/test/NameGriefer.sol:NameGriefer"]: NameGriefer$Type;
  }

  interface ContractTypesMap {
    ["NameGriefer"]: GetContractReturnType<NameGriefer$Type["abi"]>;
    ["contracts/wrapper/test/NameGriefer.sol:NameGriefer"]: GetContractReturnType<NameGriefer$Type["abi"]>;
  }
}
