// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMulticallable$Type } from "./IMulticallable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMulticallable"]: IMulticallable$Type;
    ["contracts/resolvers/IMulticallable.sol:IMulticallable"]: IMulticallable$Type;
  }

  interface ContractTypesMap {
    ["IMulticallable"]: GetContractReturnType<IMulticallable$Type["abi"]>;
    ["contracts/resolvers/IMulticallable.sol:IMulticallable"]: GetContractReturnType<IMulticallable$Type["abi"]>;
  }
}
