// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DNSRegistrar$Type } from "./DNSRegistrar";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DNSRegistrar"]: DNSRegistrar$Type;
    ["contracts/dnsregistrar/DNSRegistrar.sol:DNSRegistrar"]: DNSRegistrar$Type;
  }

  interface ContractTypesMap {
    ["DNSRegistrar"]: GetContractReturnType<DNSRegistrar$Type["abi"]>;
    ["contracts/dnsregistrar/DNSRegistrar.sol:DNSRegistrar"]: GetContractReturnType<DNSRegistrar$Type["abi"]>;
  }
}
