// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyParser$Type } from "./DummyParser";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyParser"]: DummyParser$Type;
    ["contracts/dnsregistrar/mocks/DummyParser.sol:DummyParser"]: DummyParser$Type;
  }

  interface ContractTypesMap {
    ["DummyParser"]: GetContractReturnType<DummyParser$Type["abi"]>;
    ["contracts/dnsregistrar/mocks/DummyParser.sol:DummyParser"]: GetContractReturnType<DummyParser$Type["abi"]>;
  }
}
