// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { INameResolver$Type } from "./INameResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["INameResolver"]: INameResolver$Type;
    ["contracts/resolvers/profiles/INameResolver.sol:INameResolver"]: INameResolver$Type;
  }

  interface ContractTypesMap {
    ["INameResolver"]: GetContractReturnType<INameResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/INameResolver.sol:INameResolver"]: GetContractReturnType<INameResolver$Type["abi"]>;
  }
}
