// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RRUtils$Type } from "./RRUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RRUtils"]: RRUtils$Type;
    ["contracts/dnssec-oracle/RRUtils.sol:RRUtils"]: RRUtils$Type;
  }

  interface ContractTypesMap {
    ["RRUtils"]: GetContractReturnType<RRUtils$Type["abi"]>;
    ["contracts/dnssec-oracle/RRUtils.sol:RRUtils"]: GetContractReturnType<RRUtils$Type["abi"]>;
  }
}
