// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface RRUtils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "RRUtils",
  "sourceName": "contracts/dnssec-oracle/RRUtils.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220721757aaa78ac48cb89fd9b712046fd7ceeb941951ceb405efdf1dbf052bd2c864736f6c63430008110033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220721757aaa78ac48cb89fd9b712046fd7ceeb941951ceb405efdf1dbf052bd2c864736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "RRUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RRUtils$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/dnssec-oracle/RRUtils.sol:RRUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RRUtils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "RRUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RRUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/dnssec-oracle/RRUtils.sol:RRUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RRUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "RRUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RRUtils$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/dnssec-oracle/RRUtils.sol:RRUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RRUtils$Type["abi"]>>;
}
