// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IABIResolver$Type } from "./IABIResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IABIResolver"]: IABIResolver$Type;
    ["contracts/resolvers/profiles/IABIResolver.sol:IABIResolver"]: IABIResolver$Type;
  }

  interface ContractTypesMap {
    ["IABIResolver"]: GetContractReturnType<IABIResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IABIResolver.sol:IABIResolver"]: GetContractReturnType<IABIResolver$Type["abi"]>;
  }
}
