// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FIFSRegistrar$Type } from "./FIFSRegistrar";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FIFSRegistrar"]: FIFSRegistrar$Type;
    ["contracts/registry/FIFSRegistrar.sol:FIFSRegistrar"]: FIFSRegistrar$Type;
  }

  interface ContractTypesMap {
    ["FIFSRegistrar"]: GetContractReturnType<FIFSRegistrar$Type["abi"]>;
    ["contracts/registry/FIFSRegistrar.sol:FIFSRegistrar"]: GetContractReturnType<FIFSRegistrar$Type["abi"]>;
  }
}
