// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BytesUtils$Type } from "./BytesUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BytesUtils"]: BytesUtils$Type;
    ["contracts/utils/BytesUtils.sol:BytesUtils"]: BytesUtils$Type;
  }

  interface ContractTypesMap {
    ["BytesUtils"]: GetContractReturnType<BytesUtils$Type["abi"]>;
    ["contracts/utils/BytesUtils.sol:BytesUtils"]: GetContractReturnType<BytesUtils$Type["abi"]>;
  }
}
