// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BytesUtils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BytesUtils",
  "sourceName": "contracts/utils/BytesUtils.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "offset",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "length",
          "type": "uint256"
        }
      ],
      "name": "OffsetOutOfBoundsError",
      "type": "error"
    }
  ],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c9606dd991eafac13fe7426cd8553ee2283ac243fa0d27de1d8800261af1b08064736f6c63430008110033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c9606dd991eafac13fe7426cd8553ee2283ac243fa0d27de1d8800261af1b08064736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BytesUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BytesUtils$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/utils/BytesUtils.sol:BytesUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BytesUtils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BytesUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BytesUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/utils/BytesUtils.sol:BytesUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BytesUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BytesUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BytesUtils$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/utils/BytesUtils.sol:BytesUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BytesUtils$Type["abi"]>>;
}
