// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { StringUtilsTest$Type } from "./StringUtilsTest";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StringUtilsTest"]: StringUtilsTest$Type;
    ["contracts/test/mocks/StringUtilsTest.sol:StringUtilsTest"]: StringUtilsTest$Type;
  }

  interface ContractTypesMap {
    ["StringUtilsTest"]: GetContractReturnType<StringUtilsTest$Type["abi"]>;
    ["contracts/test/mocks/StringUtilsTest.sol:StringUtilsTest"]: GetContractReturnType<StringUtilsTest$Type["abi"]>;
  }
}
