// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IBaseRegistrar$Type } from "./IBaseRegistrar";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IBaseRegistrar"]: IBaseRegistrar$Type;
    ["contracts/ethregistrar/IBaseRegistrar.sol:IBaseRegistrar"]: IBaseRegistrar$Type;
  }

  interface ContractTypesMap {
    ["IBaseRegistrar"]: GetContractReturnType<IBaseRegistrar$Type["abi"]>;
    ["contracts/ethregistrar/IBaseRegistrar.sol:IBaseRegistrar"]: GetContractReturnType<IBaseRegistrar$Type["abi"]>;
  }
}
