// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20Recoverable$Type } from "./ERC20Recoverable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Recoverable"]: ERC20Recoverable$Type;
    ["contracts/utils/ERC20Recoverable.sol:ERC20Recoverable"]: ERC20Recoverable$Type;
  }

  interface ContractTypesMap {
    ["ERC20Recoverable"]: GetContractReturnType<ERC20Recoverable$Type["abi"]>;
    ["contracts/utils/ERC20Recoverable.sol:ERC20Recoverable"]: GetContractReturnType<ERC20Recoverable$Type["abi"]>;
  }
}
