// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BulkRenewal$Type } from "./BulkRenewal";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BulkRenewal"]: BulkRenewal$Type;
    ["contracts/ethregistrar/BulkRenewal.sol:BulkRenewal"]: BulkRenewal$Type;
  }

  interface ContractTypesMap {
    ["BulkRenewal"]: GetContractReturnType<BulkRenewal$Type["abi"]>;
    ["contracts/ethregistrar/BulkRenewal.sol:BulkRenewal"]: GetContractReturnType<BulkRenewal$Type["abi"]>;
  }
}
