// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockERC20$Type } from "./MockERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockERC20"]: MockERC20$Type;
    ["contracts/test/mocks/MockERC20.sol:MockERC20"]: MockERC20$Type;
  }

  interface ContractTypesMap {
    ["MockERC20"]: GetContractReturnType<MockERC20$Type["abi"]>;
    ["contracts/test/mocks/MockERC20.sol:MockERC20"]: GetContractReturnType<MockERC20$Type["abi"]>;
  }
}
