// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PublicSuffixList$Type } from "./PublicSuffixList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PublicSuffixList"]: PublicSuffixList$Type;
    ["contracts/dnsregistrar/PublicSuffixList.sol:PublicSuffixList"]: PublicSuffixList$Type;
  }

  interface ContractTypesMap {
    ["PublicSuffixList"]: GetContractReturnType<PublicSuffixList$Type["abi"]>;
    ["contracts/dnsregistrar/PublicSuffixList.sol:PublicSuffixList"]: GetContractReturnType<PublicSuffixList$Type["abi"]>;
  }
}
