// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DNSClaimChecker$Type } from "./DNSClaimChecker";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DNSClaimChecker"]: DNSClaimChecker$Type;
    ["contracts/dnsregistrar/DNSClaimChecker.sol:DNSClaimChecker"]: DNSClaimChecker$Type;
  }

  interface ContractTypesMap {
    ["DNSClaimChecker"]: GetContractReturnType<DNSClaimChecker$Type["abi"]>;
    ["contracts/dnsregistrar/DNSClaimChecker.sol:DNSClaimChecker"]: GetContractReturnType<DNSClaimChecker$Type["abi"]>;
  }
}
