// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface NameEncoder$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "NameEncoder",
  "sourceName": "contracts/utils/NameEncoder.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122079e2977a06430592682f74a1d66ea9fd067cbd7d16b423399621913993a7bf7864736f6c63430008110033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122079e2977a06430592682f74a1d66ea9fd067cbd7d16b423399621913993a7bf7864736f6c63430008110033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "NameEncoder",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<NameEncoder$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/utils/NameEncoder.sol:NameEncoder",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<NameEncoder$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "NameEncoder",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<NameEncoder$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/utils/NameEncoder.sol:NameEncoder",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<NameEncoder$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "NameEncoder",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<NameEncoder$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/utils/NameEncoder.sol:NameEncoder",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<NameEncoder$Type["abi"]>>;
}
