// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDNSRegistrar$Type } from "./IDNSRegistrar";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDNSRegistrar"]: IDNSRegistrar$Type;
    ["contracts/dnsregistrar/IDNSRegistrar.sol:IDNSRegistrar"]: IDNSRegistrar$Type;
  }

  interface ContractTypesMap {
    ["IDNSRegistrar"]: GetContractReturnType<IDNSRegistrar$Type["abi"]>;
    ["contracts/dnsregistrar/IDNSRegistrar.sol:IDNSRegistrar"]: GetContractReturnType<IDNSRegistrar$Type["abi"]>;
  }
}
