// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LinearPremiumPriceOracle$Type } from "./LinearPremiumPriceOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LinearPremiumPriceOracle"]: LinearPremiumPriceOracle$Type;
    ["contracts/ethregistrar/LinearPremiumPriceOracle.sol:LinearPremiumPriceOracle"]: LinearPremiumPriceOracle$Type;
  }

  interface ContractTypesMap {
    ["LinearPremiumPriceOracle"]: GetContractReturnType<LinearPremiumPriceOracle$Type["abi"]>;
    ["contracts/ethregistrar/LinearPremiumPriceOracle.sol:LinearPremiumPriceOracle"]: GetContractReturnType<LinearPremiumPriceOracle$Type["abi"]>;
  }
}
