// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IVersionableResolver$Type } from "./IVersionableResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVersionableResolver"]: IVersionableResolver$Type;
    ["contracts/resolvers/profiles/IVersionableResolver.sol:IVersionableResolver"]: IVersionableResolver$Type;
  }

  interface ContractTypesMap {
    ["IVersionableResolver"]: GetContractReturnType<IVersionableResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/IVersionableResolver.sol:IVersionableResolver"]: GetContractReturnType<IVersionableResolver$Type["abi"]>;
  }
}
