// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExtendedDNSResolver$Type } from "./ExtendedDNSResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExtendedDNSResolver"]: ExtendedDNSResolver$Type;
    ["contracts/resolvers/profiles/ExtendedDNSResolver.sol:ExtendedDNSResolver"]: ExtendedDNSResolver$Type;
  }

  interface ContractTypesMap {
    ["ExtendedDNSResolver"]: GetContractReturnType<ExtendedDNSResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/ExtendedDNSResolver.sol:ExtendedDNSResolver"]: GetContractReturnType<ExtendedDNSResolver$Type["abi"]>;
  }
}
