// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyOracle$Type } from "./DummyOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyOracle"]: DummyOracle$Type;
    ["contracts/ethregistrar/DummyOracle.sol:DummyOracle"]: DummyOracle$Type;
  }

  interface ContractTypesMap {
    ["DummyOracle"]: GetContractReturnType<DummyOracle$Type["abi"]>;
    ["contracts/ethregistrar/DummyOracle.sol:DummyOracle"]: GetContractReturnType<DummyOracle$Type["abi"]>;
  }
}
