// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DummyDigest$Type } from "./DummyDigest";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DummyDigest"]: DummyDigest$Type;
    ["contracts/dnssec-oracle/digests/DummyDigest.sol:DummyDigest"]: DummyDigest$Type;
  }

  interface ContractTypesMap {
    ["DummyDigest"]: GetContractReturnType<DummyDigest$Type["abi"]>;
    ["contracts/dnssec-oracle/digests/DummyDigest.sol:DummyDigest"]: GetContractReturnType<DummyDigest$Type["abi"]>;
  }
}
