// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LowLevelCallUtils$Type } from "./LowLevelCallUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LowLevelCallUtils"]: LowLevelCallUtils$Type;
    ["contracts/utils/LowLevelCallUtils.sol:LowLevelCallUtils"]: LowLevelCallUtils$Type;
  }

  interface ContractTypesMap {
    ["LowLevelCallUtils"]: GetContractReturnType<LowLevelCallUtils$Type["abi"]>;
    ["contracts/utils/LowLevelCallUtils.sol:LowLevelCallUtils"]: GetContractReturnType<LowLevelCallUtils$Type["abi"]>;
  }
}
