// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NameResolver$Type } from "./NameResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NameResolver"]: NameResolver$Type;
    ["contracts/resolvers/profiles/NameResolver.sol:NameResolver"]: NameResolver$Type;
  }

  interface ContractTypesMap {
    ["NameResolver"]: GetContractReturnType<NameResolver$Type["abi"]>;
    ["contracts/resolvers/profiles/NameResolver.sol:NameResolver"]: GetContractReturnType<NameResolver$Type["abi"]>;
  }
}
